version: '3.8'


services:
  app:
    build: .
    user: "1000"
    ports:
      - "5001:5001"
    volumes:
      - ./files_input:/wd/files_input:ro
      - ./files_output:/wd/files_output:rw
      - ./files_output:/wd/special_folder:rw
      - ./db:/wd/db:rw
    command: --host 0.0.0.0 --port 5001
